print ("welcome to LearnLlanguage.org")
print ("where you have heard about our app")
print ("facebook")
print ("instagram")
print ("twitter")
print ("youtube")
print ("or from a friend")
print ("we are happy to have you here")
print ("lets get started")
print ("what is your name?")
name = input()
print ("welcome " + name)
print ("what language do you want to learn?")
language = input()
print ("great " + name + " you have chosen to learn " + language)
print ("how many hours a week can you dedicate to learning " + language + "?")
hours = input()
print ("awesome " + name + " you can dedicate " + hours + " hours a week to learning " + language)
print ("we will create a personalized learning plan for you")
print ("thank you for choosing LearnLlanguage.org")
print ("happy learning!")
print ("if you have any questions feel free to reach out to us at")
if language == ("Spanish"):
    print ("hola")
    print ("el hombre")
    print ("A man in spanish is 'el hombre'")
    print ("la mujer")
    print ("A women in spanish is 'la mujer")
    print ("el niño")
    print ("a boy in spanish is 'el niño'")
    print ("la niña")
    print ("a girl in spanish is 'la niña'")
    print ("wow " + name + " you are doing great!")
    print ("let's learn some more")
    print ("gracias")
    print ("thank you in spanish is 'gracias'")
    print ("por favor")
    print ("please in spanish is 'por favor'")
    print ("de nada")
    print ("you're welcome in spanish is 'de nada'")
    print ("lo siento")
    print ("sorry in spanish is 'lo siento'")
    print ("adiós")
    print ("goodbye in spanish is 'adiós'")
    print ("see you next time " + name)
elif language == ("French"):
    print ("bonjour")
    print ("hello in french is 'bonjour'")
    print ("le homme")
    print ("a man in french is 'le homme'")
    print ("la femme")
    print ("a women in french is 'la femme'")
    print ("le garçon")
    print ("a boy in french is 'le garçon'")
    print ("la fille")
    print ("a girl in french is 'la fille'")
    print ("wow " + name + " you are doing great!")
    print ("let's learn some more")